[workspace]
members = ["src/gpu_util", "src/macros", "src/native", "src/wrapper"]
resolver = "2"

[workspace.package]
authors = ["John Doe <john@doe.com>"]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
pyo3 = { version = "0.27.0" }
tokio = "1.48.0"
anyhow = { version = "1.0.100", features = ["backtrace"] }
log = "0.4.29"
napi = { version = "3.0.0", features = ["async", "serde-json"] }
napi-derive = "3.0.0"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
wgpu = "27.0.1"

[profile.release]
lto = true
strip = "symbols"
