[package]
name = "wrapper"
authors.workspace = true
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wgpu = { workspace = true }
pyo3-stub-gen = "0.17.0"
tokio = { workspace = true, features = ["rt-multi-thread"] }
pyo3 = { workspace = true, features = ["anyhow"] }
anyhow = { workspace = true }
numpy = "0.27.0"
log = { workspace = true }
gpu_util = { path = "../gpu_util" }
aperio_derive = { path = "../macros" }
napi ={ workspace = true }
napi-derive = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[[bin]]
name = "stub_gen"
path = "src/bin/stub_gen.rs"
doc = false
