[package]
name = "text_rendering"
authors.workspace = true
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
cosmic-text = "0.18.2"
gpu_util = { path = "../gpu_util" }
wgpu = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
