[package]
name = "avloader"
authors.workspace = true
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
gpu_util = { path = "../gpu_util" }
anyhow = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }

[build-dependencies]
cc = "1"
bindgen = "0.71"
